
const states = [
    { code: 'AL', name: 'Alabama', capital: 'Montgomery' },
    { code: 'AK', name: 'Alaska', capital: 'Juneau' },
    { code: 'AZ', name: 'Arizona', capital: 'Phoenix' },
    { code: 'AR', name: 'Arkansas', capital: 'Little Rock' },
    { code: 'CA', name: 'California', capital: 'Sacramento' },
    { code: 'CO', name: 'Colorado', capital: 'Denver' },
    { code: 'CT', name: 'Connecticut', capital: 'Hartford' },
    { code: 'DE', name: 'Delaware', capital: 'Dover' },
    { code: 'FL', name: 'Florida', capital: 'Tallahassee' },
    { code: 'GA', name: 'Georgia', capital: 'Atlanta' },
    { code: 'HI', name: 'Hawaii', capital: 'Honolulu' },
    { code: 'ID', name: 'Idaho', capital: 'Boise' },
    { code: 'IL', name: 'Illinois', capital: 'Springfield' },
    { code: 'IN', name: 'Indiana', capital: 'Indianapolis' },
    { code: 'IA', name: 'Iowa', capital: 'Des Moines' },
    { code: 'KS', name: 'Kansas', capital: 'Topeka' },
    { code: 'KY', name: 'Kentucky', capital: 'Frankfort' },
    { code: 'LA', name: 'Louisiana', capital: 'Baton Rouge' },
    { code: 'ME', name: 'Maine', capital: 'Augusta' },
    { code: 'MD', name: 'Maryland', capital: 'Annapolis' },
    { code: 'MA', name: 'Massachusetts', capital: 'Boston' },
    { code: 'MI', name: 'Michigan', capital: 'Lansing' },
    { code: 'MN', name: 'Minnesota', capital: 'Saint Paul' },
    { code: 'MS', name: 'Mississippi', capital: 'Jackson' },
    { code: 'MO', name: 'Missouri', capital: 'Jefferson City' },
    { code: 'MT', name: 'Montana', capital: 'Helena' },
    { code: 'NE', name: 'Nebraska', capital: 'Lincoln' },
    { code: 'NV', name: 'Nevada', capital: 'Carson City' },
    { code: 'NH', name: 'New Hampshire', capital: 'Concord' },
    { code: 'NJ', name: 'New Jersey', capital: 'Trenton' },
    { code: 'NM', name: 'New Mexico', capital: 'Santa Fe' },
    { code: 'NY', name: 'New York', capital: 'Albany' },
    { code: 'NC', name: 'North Carolina', capital: 'Raleigh' },
    { code: 'ND', name: 'North Dakota', capital: 'Bismarck' },
    { code: 'OH', name: 'Ohio', capital: 'Columbus' },
    { code: 'OK', name: 'Oklahoma', capital: 'Oklahoma City' },
    { code: 'OR', name: 'Oregon', capital: 'Salem' },
    { code: 'PA', name: 'Pennsylvania', capital: 'Harrisburg' },
    { code: 'RI', name: 'Rhode Island', capital: 'Providence' },
    { code: 'SC', name: 'South Carolina', capital: 'Columbia' },
    { code: 'SD', name: 'South Dakota', capital: 'Pierre' },
    { code: 'TN', name: 'Tennessee', capital: 'Nashville' },
    { code: 'TX', name: 'Texas', capital: 'Austin' },
    { code: 'UT', name: 'Utah', capital: 'Salt Lake City' },
    { code: 'VT', name: 'Vermont', capital: 'Montpelier' },
    { code: 'VA', name: 'Virginia', capital: 'Richmond' },
    { code: 'WA', name: 'Washington', capital: 'Olympia' },
    { code: 'WV', name: 'West Virginia', capital: 'Charleston' },
    { code: 'WI', name: 'Wisconsin', capital: 'Madison' },
    { code: 'WY', name: 'Wyoming', capital: 'Cheyenne' },
  ]
  
  export default {states}